# Site settings
title: Apigee API Studio
email: wwitman@apigee.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation site for Apigee API Studio.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username: 

# Build settings
markdown: kramdown
